*!! Package not yet meant for general public consumption !!*

This package will be an org exporter backend that exports =org-mode= to =markdown= with [[https://gohugo.io/][=hugo=]] -required TOML front-matter. =hugo= also supports YAML front-matter but planning to stick with TOML for now.

What this package is planned to do --

- Write blog posts in =org-mode=.
- For *current subtree*
  - Export the org-mode meta-data and content into a separate markdown file.
  - Do that with each save.

* TODO [0/5]
- [ ] Have =ox-hugo= be a backend derived from =ox-gfm= (=ox-gfm= needed at least for table support).
- [ ] Parse org tags to set the hugo post tags/categories in fm.
- [ ] Parse org heading to set the hugo post title in fm.
- [ ] Use title to auto-generate file name string.
- [ ] Set post date to be the same as the export date *unless* =:PUBLISHDATE:= property exists.
- [ ] Ability to set/toggle =:DRAFT: true= in property drawer. Of course that should translate to hugo post fm.
- [ ] Function to re-export the whole org file to subtree-specific markdown files
- [ ] Call =hugo= after each save.

* References
Currently the =ox-hugo.el= just contains slightly re-factored code snippets from the below 2 sources:
- http://www.holgerschurig.de/en/emacs-blog-from-org-to-hugo/
- http://whyarethingsthewaytheyare.com/setting-up-the-blog/
