*!! Package not yet meant for general public consumption !!*

What this package is planned to do:

- Write blog posts in =org-mode=.
- For *current subtree*
  - Export the org-mode meta-data and content into a separate markdown file.
  - Do that with each save.

* TODO [0/5]
- [ ] Parse org tags to set the hugo post tags/categories in fm.
- [ ] Parse org heading to set the hugo post title in fm.
- [ ] Use title to auto-generate file name string.
- [ ] Set post date to be the same as the export date *unless* =:PUBLISHDATE:= property exists.
- [ ] Ability to set/toggle =:DRAFT: true= in property drawer. Of course that should translate to hugo post fm.
- [ ] Function to re-export the whole org file to subtree-specific markdown files
- [ ] Call =hugo= after each save.

* References
Currently the =org-hugo.el= just contains slightly re-factored code snippets from the below 2 sources:
- http://www.holgerschurig.de/en/emacs-blog-from-org-to-hugo/
- http://whyarethingsthewaytheyare.com/setting-up-the-blog/
